version: 1.2.{build}
image: Visual Studio 2017
branches:
  only:
  - master
skip_commits:
  message: /\[chore\]/
init:
  - git config --global core.autocrlf true
build_script:
- ps: >-
    dotnet restore    

    dotnet build -c Release
test_script:
- ps: >-
    cd tests/codenamegenerator.lite.tests

    dotnet test -c Release --no-build